### ISSUE TITLE
The transaction could not be confirmed.

### ISSUE THREAD

**Issue by karneaud** [openchain/docker#2]
Running the latest build and keep getting the subject message.

I'm getting the following error in the console

> Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
> /#/submit:1 XMLHttpRequest cannot load http://192.168.99.100/openchain/submit. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://nossl.wallet.openchain.org' is therefore not allowed access. The response had HTTP status code 504.

The thread output gives me

> chain_1  |       Request starting HTTP/1.1 POST http://openchain:8080/submit application/json;charset=UTF-8 744
> openchain_1  | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
> openchain_1  |       Executing action method Openchain.Server.Controllers.OpenchainController.Post (Openchain.Server) with arguments ((null)) - ModelState is Valid
> nginx        | 2016/12/03 21:38:30 [error] 5#5: *20 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.99.1, server: , request: "POST /openchain/submit HTTP/1.1", upstream: "http://172.17.0.2:8080/submit", host: "192.168.99.100", referrer: "http://nossl.wallet.openchain.org/"
> nginx        | 192.168.99.1 - - [03/Dec/2016:21:38:30 +0000] "POST /openchain/submit HTTP/1.1" 504 183 "http://nossl.wallet.openchain.org/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8"
> openchain_1  | info: General[0]
> openchain_1  |       [2016-12-03 21:38:30Z] Validated transaction 333d90025b93c80b5f04096a894beee20377e8ec13c744958037f8514b96c046
> openchain_1  | info: Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor[1]
> openchain_1  |       Executing JsonResult, writing value { transaction_hash = 333d90025b93c80b5f04096a894beee20377e8ec13c744958037f8514b96c046, mutation_hash = 00f734c93b5294d799ba9f4c605e914a14a64f62b6fa1a6e39e098b88c20df07 }.
> openchain_1  | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
> openchain_1  |       Executed action Openchain.Server.Controllers.OpenchainController.Post (Openchain.Server) in 60047.4225ms
> openchain_1  | info: Microsoft.AspNetCore.Server.Kestrel[14]
> openchain_1  |       Connection id "0HL0RN8EOF500" communication error.
> openchain_1  | Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe
> openchain_1  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
> openchain_1  |       Request finished in 60051.2961ms 200 application/json; charset=utf-8

Any ideas as to what could be the problem? This used to work fine until the upgrade

**Comment by Flavien** [comment]
Which version of openchain are you running, and are you running behind Nginx?

**Comment by karneaud** [comment]
@Flavien I'm running off your latest docker build.

**Comment by Flavien** [comment]
I've updated the Nginx configuration, there was an issue with the existing config and Kestrel 1.1.

[This](https://github.com/openchain/docker/blob/master/templates/nginx.conf) is the correct configuration file to use for Nginx.
